BoxLayout:
	orientation:'horizontal'
	WuziqiWidget:
		id:board
		canvas.before:
			Color:
				rgba: 249/255., 214/255., 91/255., 1 # your color here
			Rectangle:
				pos:root.pos
				size: root.size
		size_hint:.8,1
	BoxLayout:
		orientation:'vertical'
		size_hint:.2,1
		Label:
			text:''
		Button:
			size_hint:1,.2
			text:'重新开始'
			background_color:168/255., 217/255.,209/255.,1
			on_press:board.restart()
		
		